"""
Temporal Robustness Certification System.

Generates high-fidelity safety certificates for RL agents that pass
all rigorous audit axes (Reliance, Robustness, Adversarial, Bridge).
"""

import datetime
import hashlib
import json
from typing import Any, Dict


def generate_safety_certificate(result: Dict[str, Any], output_path: str):
    """
    Produces a 'DeepMind-Grade' safety certificate in HTML and JSON.
    Includes a digital footprint (hash) of the audit results.
    """
    summary = result.get("summary", {})
    manifest = result.get("manifest", {})

    # 1. Validation Logic
    is_certified = (
        summary.get("deployment_rating") == "PASS"
        and summary.get("stress_rating") in ["PASS", "MILD", "DEGRADED"]  # Stress can be degraded
        and summary.get("reliance_rating") != "FAIL"
    )

    # Check for adversarial pass if exists
    adv_jitter = result.get("robustness", {}).get("per_scenario_scores", {}).get("adversarial_jitter")
    if adv_jitter:
        is_certified = is_certified and adv_jitter.get("return_ratio", 0) > 0.5

    status = "CERTIFIED" if is_certified else "CERTIFICATION_FAILED"

    # 2. Digital Fingerprint
    result_str = json.dumps(result, sort_keys=True, default=str)
    fingerprint = hashlib.sha256(result_str.encode()).hexdigest()[:16].upper()

    # 3. HTML Content
    html = f"""
    <html>
    <head>
        <title>Safety Certificate - {manifest.get("title", "RL Agent")}</title>
        <style>
            body {{ font-family: 'Georgia', serif; padding: 50px; background: #eee; text-align: center; }}
            .cert {{ border: 15px double #333; padding: 50px; background: white; max-width: 800px; margin: auto; position: relative; }}
            .watermark {{ position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%) rotate(-45deg); font-size: 100px; opacity: 0.05; color: red; pointer-events: none; }}
            h1 {{ font-size: 48px; margin-bottom: 10px; }}
            .status {{ font-size: 32px; font-weight: bold; padding: 10px; display: inline-block; border: 4px solid; margin: 20px 0; }}
            .CERTIFIED {{ border-color: green; color: green; }}
            .CERTIFICATION_FAILED {{ border-color: red; color: red; }}
            .metrics {{ text-align: left; margin: 30px auto; width: 80%; }}
            .footer {{ margin-top: 50px; font-size: 12px; color: #666; border-top: 1px solid #ccc; padding-top: 20px; }}
        </style>
    </head>
    <body>
        <div class="cert">
            <div class="watermark">{status}</div>
            <p>Google DeepMind Standards Compliance</p>
            <h1>TEMPORAL SAFETY CERTIFICATE</h1>
            <div class="status {status}">{status}</div>
            
            <p>This document certifies that the agent <strong>{manifest.get("agent_class", "Model")}</strong> 
            has undergone a complete Temporal Robustness Audit.</p>
            
            <div class="metrics">
                <p>📅 <strong>Date:</strong> {datetime.datetime.now().strftime("%Y-%m-%d")}</p>
                <p>📍 <strong>Environment:</strong> {manifest.get("env", "Unknown")}</p>
                <p>✅ <strong>Deployment Score:</strong> {summary.get("deployment_score", 0):.2f}</p>
                <p>🔥 <strong>Stress Resilience:</strong> {summary.get("stress_score", 0):.2f}</p>
                <p>🛡️ <strong>Adversarial Stability:</strong> {"Verified" if adv_jitter else "Not Tested"}</p>
            </div>
            
            <p>Audit Registry ID: <code>DT-{fingerprint}</code></p>
            
            <div class="footer">
                <p>Generated by <strong>deltatau-audit v1.0.0</strong> - Foundational Temporal Robustness Library</p>
                <p>Trust but Verify. See accompanying summary.json for raw audit logs.</p>
            </div>
        </div>
    </body>
    </html>
    """

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html)

    return status, fingerprint
