from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from deltatau_audit.badge import generate_badges
from deltatau_audit.ci import generate_ci_summary
from deltatau_audit.report import generate_report
from tests.conftest import make_result

_GOLDEN_DIR = Path(__file__).resolve().parent / "golden"


def _load_golden(name: str) -> dict[str, Any]:
    return json.loads((_GOLDEN_DIR / name).read_text(encoding="utf-8"))


def _round_floats(value: Any) -> Any:
    if isinstance(value, float):
        return round(value, 6)
    if isinstance(value, list):
        return [_round_floats(item) for item in value]
    if isinstance(value, dict):
        return {key: _round_floats(item) for key, item in value.items()}
    return value


def _build_contract_result() -> dict[str, Any]:
    result = make_result()
    for key in ("schema_version", "manifest", "diagnosis"):
        result.pop(key, None)
    return result


def _canonicalize_report_summary(data: dict[str, Any]) -> dict[str, Any]:
    canonical = _round_floats(json.loads(json.dumps(data)))
    canonical["_version"] = "<version>"
    canonical["_timestamp"] = "<timestamp>"

    manifest = canonical["manifest"]
    runtime = manifest.get("runtime", {})
    git = manifest.get("git", {})
    dependencies = manifest.get("dependencies", {})
    manifest["created_at"] = "<timestamp>"
    manifest["runtime"] = {"keys": sorted(runtime.keys())}
    manifest["git"] = {"keys": sorted(git.keys()), "available": "<bool>"}
    manifest["dependencies"] = {
        "keys": sorted(dependencies.keys()),
        "available": "<bool>",
        "lockfile_names": sorted((dependencies.get("lockfile_hashes") or {}).keys()),
    }
    return canonical


def _canonicalize_ci_summary(data: dict[str, Any]) -> dict[str, Any]:
    canonical = _round_floats(json.loads(json.dumps(data)))
    canonical["_version"] = "<version>"
    canonical["_timestamp"] = "<timestamp>"
    return canonical


def test_report_summary_matches_golden_contract(tmp_path: Path):
    generate_report(_build_contract_result(), str(tmp_path), title="Contract Test")

    summary_path = tmp_path / "summary.json"
    summary = json.loads(summary_path.read_text(encoding="utf-8"))

    assert _canonicalize_report_summary(summary) == _load_golden(
        "report_summary_contract.json"
    )


def test_ci_summary_matches_golden_contract(tmp_path: Path):
    ci_summary = generate_ci_summary(
        _build_contract_result(),
        out_dir=tmp_path,
        gate_mode="score",
    )

    assert _canonicalize_ci_summary(ci_summary) == _load_golden(
        "ci_summary_contract.json"
    )


def test_report_and_badges_follow_file_contract(tmp_path: Path):
    generate_report(_build_contract_result(), str(tmp_path), title="Contract Test")

    summary_path = tmp_path / "summary.json"
    badge_paths = generate_badges(str(summary_path), str(tmp_path), prefix="contract")

    expected_files = {
        "summary.json",
        "index.html",
        "robustness_bars.png",
        "contract-deployment.svg",
        "contract-stress.svg",
        "contract-reliance.svg",
        "contract-status.svg",
    }
    actual_files = {path.name for path in tmp_path.iterdir()}

    assert expected_files.issubset(actual_files)
    assert not (tmp_path / "return_vs_speed.png").exists()
    assert not (tmp_path / "reliance_rmse.png").exists()
    assert not (tmp_path / "reliance_bars.png").exists()
    assert not (tmp_path / "quadrant.png").exists()

    assert {Path(path).name for path in badge_paths.values()} == {
        "contract-deployment.svg",
        "contract-stress.svg",
        "contract-reliance.svg",
        "contract-status.svg",
    }

    html = (tmp_path / "index.html").read_text(encoding="utf-8")
    assert "<title>Contract Test</title>" in html
    assert "Deployment Ready" in html
    assert "1 DEGRADED scenario: speed_5x" in html
    assert "Generated by <code>deltatau-audit</code> v" in html
