"""CI integration: exit codes, summary JSON/MD for pipeline gates.

Exit codes:
    0 = pass  (deployment >= threshold, stress >= threshold)
    1 = warn  (deployment passes but stress fails)
    2 = fail  (deployment below threshold)
"""

import datetime
import json
import os
from typing import Dict


def compute_exit_code(summary: Dict,
                      deploy_threshold: float = 0.80,
                      stress_threshold: float = 0.50) -> int:
    """Determine CI exit code from audit summary.

    Returns:
        0 = pass, 1 = warn (stress only), 2 = fail (deployment)
    """
    dep_score = summary.get("deployment_score", 1.0)
    str_score = summary.get("stress_score", 1.0)

    if dep_score < deploy_threshold:
        return 2  # fail
    if str_score < stress_threshold:
        return 1  # warn
    return 0  # pass


def write_ci_summary(summary: Dict, robustness: Dict,
                     output_dir: str,
                     deploy_threshold: float = 0.80,
                     stress_threshold: float = 0.50) -> int:
    """Write ci_summary.json and ci_summary.md, return exit code.

    Args:
        summary: audit_result["summary"]
        robustness: audit_result["robustness"]
        output_dir: where to write files
        deploy_threshold: deployment return ratio threshold for pass
        stress_threshold: stress return ratio threshold for warn

    Returns:
        Exit code (0/1/2)
    """
    os.makedirs(output_dir, exist_ok=True)
    exit_code = compute_exit_code(summary, deploy_threshold, stress_threshold)

    status = {0: "pass", 1: "warn", 2: "fail"}[exit_code]

    # Compact JSON
    ci_json = {
        "status": status,
        "exit_code": exit_code,
        "deployment_score": summary.get("deployment_score"),
        "deployment_rating": summary.get("deployment_rating"),
        "stress_score": summary.get("stress_score"),
        "stress_rating": summary.get("stress_rating"),
        "thresholds": {
            "deployment": deploy_threshold,
            "stress": stress_threshold,
        },
    }

    # Add worst scenarios
    deploy_info = robustness.get("deployment", {})
    stress_info = robustness.get("stress", {})
    if deploy_info:
        wc = deploy_info.get("worst_case", {})
        ci_json["deployment_worst"] = wc.get("scenario")
    if stress_info:
        wc = stress_info.get("worst_case", {})
        ci_json["stress_worst"] = wc.get("scenario")

    # Traceability
    from . import __version__
    ci_json["_version"] = __version__
    ci_json["_timestamp"] = datetime.datetime.utcnow().isoformat() + "Z"

    json_path = os.path.join(output_dir, "ci_summary.json")
    with open(json_path, "w") as f:
        json.dump(ci_json, f, indent=2)

    # Markdown summary (one-liner for PR comments)
    dep_score = summary.get("deployment_score", 0)
    dep_rating = summary.get("deployment_rating", "?")
    str_score = summary.get("stress_score", 0)
    str_rating = summary.get("stress_rating", "?")

    icon = {"pass": "✅", "warn": "⚠️", "fail": "❌"}[status]

    md_lines = [
        f"## {icon} Time Robustness Audit: **{status.upper()}**",
        "",
        f"| Axis | Rating | Score | Threshold |",
        f"|------|--------|-------|-----------|",
        f"| Deployment | **{dep_rating}** | {dep_score:.2f} | {deploy_threshold:.2f} |",
        f"| Stress | **{str_rating}** | {str_score:.2f} | {stress_threshold:.2f} |",
    ]

    # Scenario breakdown
    per_scenario = robustness.get("per_scenario_scores", {})
    if per_scenario:
        md_lines += ["", "**Scenarios:**", ""]
        for sc_name, sc in per_scenario.items():
            ret = sc["return_ratio"] * 100
            flag = " ⚠️" if ret < 80 else ""
            md_lines.append(f"- {sc_name}: {ret:.0f}%{flag}")

    md_lines.append("")
    md_lines.append(f"*Generated by deltatau-audit v{__version__}*")

    md_path = os.path.join(output_dir, "ci_summary.md")
    with open(md_path, "w", encoding="utf-8") as f:
        f.write("\n".join(md_lines))

    return exit_code
