"""
The Generative Researcher: Automated Technical Report Generator.

Converts audit JSON results into a LaTeX-formatted Technical Report.
Supports arXiv-style templates and statistical summary tables.
"""

import json
import os
import argparse

LATEX_TEMPLATE = r"""
\documentclass{{article}}
\usepackage[utf8]{{inputenc}}
\usepackage{{booktabs}}
\usepackage{{graphicx}}
\usepackage{{hyperref}}

	itle{{Temporal Robustness Audit: Technical Report}}
\author{{Generated by deltatau-audit v1.1.0}}
\date{{	oday}}

\begin{{document}}

\maketitle

\section{{Executive Summary}}
This report details the temporal robustness evaluation of the RL agent 	extbf{{{agent_class}}} 
operating in the 	extbf{{{env}}} environment. 

\begin{{itemize}}
    \item 	extbf{{Deployment Score:}} {deployment_score:.2f} ({deployment_rating})
    \item 	extbf{{Stress Resilience:}} {stress_score:.2f} ({stress_rating})
    \item 	extbf{{Registry ID:}} DT-{fingerprint}
\end{{itemize}}

\section{{Methodology: The 2-Axis Audit}}
We employ the 2-axis audit framework consisting of:
\begin{{enumerate}}
    \item 	extbf{{Reliance Axis}}: Measuring causal dependence on internal time representations.
    \item 	extbf{{Robustness Axis}}: Stress-testing against jitter, latency, and frequency spikes.
\end{{enumerate}}

\section{{Detailed Results}}
The table below summarizes performance across critical robustness scenarios.

\begin{{table}}[h]
\centering
\begin{{tabular}{llrr}
	oprule
Scenario & Category & Return Ratio & Significant? 
\midrule
{table_rows}
\bottomrule
\end{{tabular}}
\caption{{Performance degradation across temporal perturbation scenarios.}}
\end{{table}}

\section{{Failure Analysis \& Recommendations}}
{failure_logic}

\section{{Conclusion}}
The agent is classified into the 	extbf{{{quadrant}}} quadrant. 
{prescription}

\end{{document}}
"""

def generate_tex(summary_path: str, output_path: str):
    if not os.path.exists(summary_path):
        print(f"Error: {summary_path} not found.")
        return

    with open(summary_path, 'r') as f:
        data = json.load(f)

    summary = data.get("summary", {})
    manifest = data.get("manifest", {})
    robustness = data.get("robustness", {})
    scores = robustness.get("per_scenario_scores", {})

    # Build Table Rows
    rows = []
    for sc, info in scores.items():
        sig = "Yes" if info.get("significant") else "No"
        rows.append(f"{sc.replace('_', ' ')} & - & {info['return_ratio']:.2f} & {sig} ")
    table_rows = "
".join(rows)

    # Failure logic
    diagnosis = data.get("diagnosis", {})
    failure_logic = diagnosis.get("summary_line", "No critical failures detected.")
    if diagnosis.get("issues"):
        failure_logic += f"

Primary Pattern: {diagnosis['primary_pattern']}

Fix Recommendation: {diagnosis['fix_recommendation']}"

    # Fingerprint (mock if missing)
    fingerprint = summary.get("fingerprint", "N/A")

    tex = LATEX_TEMPLATE.format(
        agent_class=manifest.get("agent_class", "RLAgent"),
        env=manifest.get("env", "UnknownEnv"),
        deployment_score=summary.get("deployment_score", 0),
        deployment_rating=summary.get("deployment_rating", "N/A"),
        stress_score=summary.get("stress_score", 0),
        stress_rating=summary.get("stress_rating", "N/A"),
        fingerprint=fingerprint,
        table_rows=table_rows,
        failure_logic=failure_logic,
        quadrant=summary.get("quadrant", "unknown"),
        prescription=summary.get("prescription", "")
    )

    with open(output_path, 'w') as f:
        f.write(tex)
    
    print(f"Technical Report (LaTeX) generated: {output_path}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("summary", help="Path to summary.json")
    parser.add_argument("--out", default="report.tex", help="Output .tex file")
    args = parser.parse_args()
    generate_tex(args.summary, args.out)
